INSERT INTO eurovision.paises (pais, code_pais) VALUES
('Albania', 'ALB'),
('Andorra', 'AND'),
('Armenia', 'ARM'),
('Austria', 'AUT'),
('Azerbaijan', 'AZE'),
('Belarus', 'BLR'),
('Belgium', 'BEL'),
('Bosnia and Herzegovina', 'BIH'),
('Bulgaria', 'BGR'),
('Croatia', 'HRV'),
('Cyprus', 'CYP'),
('Czechia', 'CZE'),
('Denmark', 'DNK'),
('Estonia', 'EST'),
('Finland', 'FIN'),
('France', 'FRA'),
('Georgia', 'GEO'),
('Germany', 'DEU'),
('Greece', 'GRC'),
('Hungary', 'HUN'),
('Iceland', 'ISL'),
('Ireland', 'IRL'),
('Italy', 'ITA'),
('Kazakhstan', 'KAZ'),
('Latvia', 'LVA'),
('Liechtenstein', 'LIE'),
('Lithuania', 'LTU'),
('Luxembourg', 'LUX'),
('Malta', 'MLT'),
('Moldova', 'MDA'),
('Monaco', 'MCO'),
('Montenegro', 'MNE'),
('Netherlands', 'NLD'),
('Norway', 'NOR'),
('Poland', 'POL'),
('Portugal', 'PRT'),
('Republic of North Macedonia', 'MKD'),
('Romania', 'ROU'),
('Russia', 'RUS'),
('San Marino', 'SMR'),
('Serbia', 'SRB'),
('Slovakia', 'SVK'),
('Slovenia', 'SVN'),
('Spain', 'ESP'),
('Sweden', 'SWE'),
('Switzerland', 'CHE'),
('Ukraine', 'UKR'),
('United Kingdom', 'GBR'),
('Vatican City', 'VAT');