INSERT INTO eurovision.actuaciones (
    nombre_artista, code_pais, titulo_cancion, url_artista
) VALUES
('Kyle Alessandro', 'NOR', 'Lighter', 'WReEi3jLRFQ'), -- 'https://youtu.be/embed/WReEi3jLRFQ'),
('Laura Thorn', 'LUX', 'La poupée monte le son', 'jMY-eUDTs0Q'), -- 'https://youtu.be/embed/jMY-eUDTs0Q'),
('Tommy Cash', 'EST', 'Espresso Macchiato', 'F3wsy8bywXQ'), -- 'https://youtu.be/embed/F3wsy8bywXQ'),
('Katarsis', 'LTU', 'Tavo akys', '2vLHs89Akzo'), -- 'https://youtu.be/embed/2vLHs89Akzo'),
('Melody', 'ESP', 'Esa diva', 'BvVxhbCW9rw'), -- 'https://www.youtube.com/embed/BvVxhbCW9rw'),
('Ziferblat', 'UKR', 'Bird of Pray', '0Jc02OFU42w'), -- 'https://youtu.be/embed/0Jc02OFU42w'),
('Remember Monday', 'GBR', 'What the Hell Just Happened?', '-hu6R3ZnOdY'), -- 'https://youtu.be/embed/-hu6R3ZnOdY'),
('JJ', 'AUT', 'Wasted Love', 'coGaxAWtp58'), -- 'https://youtu.be/embed/coGaxAWtp58'),
('Væb', 'ISL', 'Róa', 'f3mAIpm5QxI'), -- 'https://youtu.be/embed/f3mAIpm5QxI'),
('Tautumeitas', 'LVA', 'Bur man laimi', 'tRTfxUJtDOs'), -- 'https://youtu.be/embed/tRTfxUJtDOs'),
('Claude', 'NLD', 'C’est la vie', 'Wb8-gbgan80'), -- 'https://youtu.be/embed/Wb8-gbgan80'),
('Erika Vikman', 'FIN', 'Ich komme', 'Kg3QoTpnqyw'), -- 'https://youtu.be/embed/Kg3QoTpnqyw'),
('Lucio Corsi', 'ITA', 'Volevo essere un duro', 'CyoY1fiVIjM'), -- 'https://youtu.be/embed/CyoY1fiVIjM'),
('Justyna Steczkowska', 'POL', 'Gaja', 'NQXhvclWuPE'), -- 'https://youtu.be/embed/NQXhvclWuPE'),
('Abor & Tynna', 'DEU', 'Baller', 'xF_sNQXP5g8'), -- 'https://youtu.be/embed/xF_sNQXP5g8'),
('Klavdia', 'GRC', 'Asteromáta', 'OP9n_cO-6V4'), -- 'https://youtu.be/embed/OP9n_cO-6V4'),
('Parg', 'ARM', 'Survivor', '5sXbxyQ5K0M'), -- 'https://youtu.be/embed/5sXbxyQ5K0M'),
('Zoë Më', 'CHE', 'Voyage', 'F4lALgxBiYI'), -- 'https://youtu.be/embed/F4lALgxBiYI'),
('Miriana Conte', 'MLT', 'Serving', '2AN3vvLORuw'), -- 'https://youtu.be/embed/2AN3vvLORuw'),
('Napa', 'PRT', 'Deslocado', '6QRHcLJS0T0'), -- 'https://youtu.be/embed/6QRHcLJS0T0'),
('Sissal', 'DNK', 'Hallucination', 'Q_ND8mF9d3c'), -- 'https://youtu.be/embed/Q_ND8mF9d3c'),
('KAJ', 'SWE', 'Bara bada bastu', 'WK3HOMhAeQY'), -- 'https://youtu.be/embed/WK3HOMhAeQY'),
('Louane', 'FRA', 'Maman', 'TUyvT65c9ok'), -- 'https://youtu.be/embed/TUyvT65c9ok'),
('Gabry Ponte', 'SMR', 'Tutta l’Italia', 'Le3WpaLYRvE'), -- 'https://youtu.be/embed/Le3WpaLYRvE'),
('Shkodra Elektronike', 'ALB', 'Zjerm', 'cwVL1dbjqj4'); -- 'https://youtu.be/embed/cwVL1dbjqj4');