INSERT INTO eurovision.actuaciones (nombre_artista, code_pais, titulo_cancion) VALUES
('Amaya García', 'ESP', 'Vivir Mi Vida'),
('Luca Rossi', 'ITA', 'La Dolce Vita'),
('Sophie Leclerc', 'FRA', 'Paris Mon Amour'),
('John Smith', 'GBR', 'I Believe in Love'),
('Lena Müller', 'DEU', 'Lichter Der Nacht'),
('Maria Martínez', 'MLT', 'Cielo Azul'),
('Marek Kowalski', 'POL', 'Piękno Świata'),
('Isabella Rossi', 'SVK', 'Fino Alla Fine'),
('Pierre Dupont', 'BEL', 'Liberté'),
('Elena Ivanova', 'RUS', 'Zvezdy na Nebe'),
('Lars Johansson', 'SWE', 'Nordic Dreams'),
('George Adams', 'NOR', 'The Power of Love'),
('Victor Moreau', 'CHE', 'Amour Toujours'),
('Daniela López', 'NLD', 'Vuela Alto'),
('Sandro Giordano', 'GEO', 'Sogno Infinito'),
('Nina Petrova', 'BGR', 'Serebryanyy Gorod'),
('Marek Nowak', 'HRV', 'Dobar Osjećaj'),
('Alicja Kwiatkowska', 'LVA', 'Ziemia Ciepła');